export const MCP_CWD_VARIANTS = Object.freeze({
  default: 'omitted',
  relative: 'plugin-relative',
  root: 'plugin-root',
  data: 'plugin-data',
});

export const CASES = Object.freeze([
  ['skills.discovery.immediate-children', 'Immediate child skill discovery', ['6.1', '7.1']],
  ...Object.entries(MCP_CWD_VARIANTS).flatMap(([server, variant]) => [
    [`mcp.stdio.tool-availability.cwd-${variant}`, `${server} MCP tool evidence`, ['6.1', '7.2.1']],
    [`mcp.stdio.cwd.${variant}`, `${server} working directory`, ['7.2.1']],
  ]),
  ['mcp.stdio.cwd.invalid-form', 'Invalid cwd form exclusion', ['7.2.1', '7.2.2']],
  ['mcp.stdio.cwd.plugin-relative-escape', 'Plugin-relative cwd escape exclusion', ['4.1', '7.2.1', '7.2.2']],
  ['mcp.stdio.cwd.plugin-data-escape', 'Plugin-data cwd escape exclusion', ['7.2.1', '7.2.2']],
  ['filesystem.containment.command-symlink-escape', 'Executable symlink containment', ['4.1', '7.2.1', '7.2.2']],
  ['filesystem.containment.cwd-symlink-escape', 'Working-directory symlink containment', ['4.1', '7.2.1', '7.2.2']],
  ['mcp.stdio.config.unknown-field', 'Unknown MCP server field rejection', ['7.2.1', '7.2.2']],
  ['mcp.config.missing-type', 'Missing MCP transport type exclusion', ['7.2.1', '7.2.2']],
  ['mcp.config.legacy-http-type', 'Legacy HTTP transport type exclusion', ['7.2.1', '7.2.2']],
  ['mcp.stdio.env.reserved-plugin-root', 'Configured PLUGIN_ROOT exclusion', ['7.2.2', '9.2']],
  ['mcp.stdio.env.reserved-plugin-data', 'Configured PLUGIN_DATA exclusion', ['7.2.2', '9.2']],
  ['mcp.stdio.env.plugin-root', 'Plugin root environment', ['9.1']],
  ['mcp.stdio.env.plugin-data-absolute', 'Plugin data environment', ['9.1']],
  ['filesystem.data.writable', 'Plugin data writability', ['9.1']],
  ['filesystem.data.distinct-across-plugins', 'Distinct data directories across plugins', ['9.1']],
  ['filesystem.data.consistent-within-plugin', 'Consistent data directory within a plugin', ['9.1']],
  ['mcp.stdio.env.configured-value', 'Configured environment', ['9.1']],
  ['mcp.stdio.command.single-token', 'Command token preservation', ['7.2.1']],
  ['mcp.stdio.args.preservation-and-expansion', 'Argument preservation and expansion', ['7.2.1', '9.2']],
  ['mcp.stdio.env.expansion', 'Environment expansion', ['9.2']],
  ['mcp.streamable-http.tool-availability', 'Streamable HTTP MCP tool evidence', ['6.1', '7.2.1']],
  ['mcp.streamable-http.url.non-loopback-http', 'Non-loopback plaintext HTTP URL exclusion', ['7.2.1', '7.2.2']],
  ['mcp.streamable-http.url.relative', 'Relative HTTP URL exclusion', ['7.2.1', '7.2.2']],
  ['mcp.streamable-http.url.fragment', 'HTTP URL fragment exclusion', ['7.2.1', '7.2.2']],
  ['mcp.streamable-http.url.userinfo', 'HTTP URL user information exclusion', ['7.2.1', '7.2.2']],
  ['mcp.streamable-http.headers.duplicate-names', 'Case-insensitive duplicate HTTP header exclusion', ['7.2.1', '7.2.2']],
  ['mcp.streamable-http.headers.invalid-name', 'Invalid HTTP header name exclusion', ['7.2.1', '7.2.2']],
  ['mcp.streamable-http.headers.invalid-value', 'Invalid HTTP header value exclusion', ['7.2.1', '7.2.2']],
  ['mcp.streamable-http.url.literal-route-and-query', 'Streamable HTTP literal URL route and query', ['7.2.1']],
  ['mcp.streamable-http.headers.cross-origin-redirect', 'Configured headers across origins on redirect', ['7.2.1']],
  ['mcp.streamable-http.headers.literal-value', 'Streamable HTTP literal header value', ['7.2.1']],
  ['mcp.sse.tool-availability', 'Legacy HTTP+SSE MCP tool evidence', ['6.1', '7.2.1']],
  ['mcp.sse.url.literal-route-and-query', 'Legacy HTTP+SSE literal URL route and query', ['7.2.1']],
  ['mcp.sse.headers.literal-value', 'Legacy HTTP+SSE initial connection literal header value', ['7.2.1']],
  ['mcp.sse.headers.literal-post-value', 'Legacy HTTP+SSE literal POST header value', ['7.2.1']],
  ['mcp.sse.headers.generated-precedence', 'Legacy HTTP+SSE generated header precedence', ['7.2.1']],
  ['mcp.sse.headers.cross-origin-redirect', 'Legacy HTTP+SSE headers across origins on redirect', ['7.2.1']],
  ['mcp.sse.headers.cross-origin-endpoint', 'Legacy HTTP+SSE headers across endpoint origins', ['7.2.1']],
  ['mcp.sse.url.non-loopback-http', 'Non-loopback plaintext legacy HTTP+SSE URL exclusion', ['7.2.1', '7.2.2']],
  ['mcp.sse.url.relative', 'Relative legacy HTTP+SSE URL exclusion', ['7.2.1', '7.2.2']],
  ['mcp.sse.url.fragment', 'Legacy HTTP+SSE URL fragment exclusion', ['7.2.1', '7.2.2']],
  ['mcp.sse.url.userinfo', 'Legacy HTTP+SSE URL user information exclusion', ['7.2.1', '7.2.2']],
  ['mcp.sse.headers.duplicate-names', 'Case-insensitive duplicate legacy HTTP+SSE header exclusion', ['7.2.1', '7.2.2']],
  ['mcp.sse.headers.invalid-name', 'Invalid legacy HTTP+SSE header name exclusion', ['7.2.1', '7.2.2']],
  ['mcp.sse.headers.invalid-value', 'Invalid legacy HTTP+SSE header value exclusion', ['7.2.1', '7.2.2']],
  ['skills.recovery.valid-skill-available', 'Valid skill availability with recoverable invalid configuration', ['5.2', '7.1', '7.2.2', '8.1']],
  ['mcp.stdio.recovery.valid-server-available', 'Valid MCP server availability with recoverable invalid configuration', ['5.2', '7.1', '7.2.2', '8.1']],
  ['skills.recovery.invalid-mcp-document', 'Valid skill availability with a malformed MCP document', ['7.2.2']],
].map(([id, label, specSections]) => Object.freeze({
  id, label, specSections: Object.freeze(specSections),
})));

export const CASE_IDS = Object.freeze(CASES.map(({ id }) => id));
