import { build } from 'esbuild';
import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';

for (const plugin of ['agent-plugins-conformance-core', 'agent-plugins-conformance-recovery']) {
  const directory = `plugins/${plugin}`;
  const result = await build({
    entryPoints: [`${directory}/src/probe.mjs`], bundle: true, platform: 'node', target: 'node22',
    format: 'esm', outfile: `${directory}/dist/probe.mjs`, metafile: true, legalComments: 'inline',
    banner: { js: '// Generated by pnpm build. Do not edit; third-party licenses: ../THIRD_PARTY_NOTICES.md\nimport { createRequire as __createRequire } from "node:module"; const require = __createRequire(import.meta.url);' },
  });
  // Carry complete licenses for packages whose source is actually bundled.
  const packages = new Map();
  for (const input of Object.keys(result.metafile.inputs).filter((name) => name.includes('node_modules/'))) {
    let directory = dirname(resolve(input));
    while (directory !== dirname(directory)) {
      try {
        const info = JSON.parse(await readFile(join(directory, 'package.json'), 'utf8'));
        if (info.name && info.version) {
          const key = `${info.name}@${info.version}`;
          if (!packages.has(key)) {
            let license;
            for (const filename of ['LICENSE', 'LICENSE.md', 'LICENSE.txt', 'license', 'license.md']) {
              try { license = await readFile(join(directory, filename), 'utf8'); break; } catch {}
            }
            if (!license) throw new Error(`Missing bundled license for ${key}`);
            packages.set(key, license.trim());
          }
          break;
        }
      } catch (error) { if (error.code !== 'ENOENT') throw error; }
      directory = dirname(directory);
    }
  }
  await mkdir(`${directory}/dist`, { recursive: true });
  await writeFile(`${directory}/THIRD_PARTY_NOTICES.md`, '# Bundled third-party notices\n\nGenerated by `pnpm build` from packages included in `dist/probe.mjs`.\n\n' + [...packages].sort(([a], [b]) => a.localeCompare(b)).map(([name, license]) => `## ${name}\n\n\`\`\`text\n${license}\n\`\`\`\n`).join('\n'));
}

// Keep each installable plugin's license notices with its runtime and docs.
for (const plugin of ['agent-plugins-conformance', 'agent-plugins-conformance-core', 'agent-plugins-conformance-recovery', 'agent-plugins-conformance-invalid-mcp']) {
  await mkdir(`plugins/${plugin}/LICENSES`, { recursive: true });
  for (const file of ['LICENSE.md', 'LICENSES/Apache-2.0.txt', 'LICENSES/CC-BY-4.0.txt']) {
    await copyFile(file, `plugins/${plugin}/${file}`);
  }
}
